# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-6c50ab8b-0fa6-4aaf-8004-a7f73d3ee6e6";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-6c50ab8b-0fa6-4aaf-8004-a7f73d3ee6e6".device = "/dev/disk/by-uuid/6c50ab8b-0fa6-4aaf-8004-a7f73d3ee6e6";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/435A-5795";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-b7284a86-a5fd-4788-a7b7-7c070be06732"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
