# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "thunderbolt" "usb_storage" "usbhid" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "tipc" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-69480e82-feb4-45cd-9c3a-3e9a0418fb0d";
      fsType = "xfs";
    };

  fileSystems."/code" =
    { device = "/dev/disk/by-uuid/5345d8d1-0c1b-43b3-9d5e-ae0f21b5940b";
      fsType = "xfs";
    };

  boot.initrd.luks.devices."luks-69480e82-feb4-45cd-9c3a-3e9a0418fb0d".device = "/dev/disk/by-uuid/69480e82-feb4-45cd-9c3a-3e9a0418fb0d";
  boot.initrd.luks.devices."luks-729c3b73-2eba-4770-b3a0-34771db29e26".device = "/dev/disk/by-uuid/729c3b73-2eba-4770-b3a0-34771db29e26";
  boot.initrd.luks.devices."luks-6cfbd371-0e66-47c7-890e-24cc63448a5d".device = "/dev/disk/by-uuid/6cfbd371-0e66-47c7-890e-24cc63448a5d";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A0DD-76D7";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-729c3b73-2eba-4770-b3a0-34771db29e26"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
